# values.yaml
replicaCount: 1
image:
  repository: ghcr.io/curiousjaki/ci-go-project
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}