name: Test

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get
      run: go get

    - name: Test
      run: go test