name: Test

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [ "main" ]

jobs:
  check_env:
    runs-on: ubuntu-latest
    steps:
    - name: Check ENV variable
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
          echo "TEST_STATUS=SUCCESS" >> $GITHUB_ENV
          exit 0
        else
          echo "TEST_STATUS=FAIL" >> $GITHUB_ENV
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get
      run: go get

    - name: Test
      run: go test